### ISSUE TITLE
Order created snippets

### ISSUE THREAD

**Issue by sandyjmh** [mantisbt-plugins/Snippets#34]
Have snippets ordered alphabetically to allow easier navigation. Or provide alternate way to manage snippets (grouping, categories with expand/collapse options perhaps).

**Comment by dregad** [comment]
As far as I can tell, Snippets **are** ordered alphabetically[[1]]...

[1]: https://github.com/mantisbt-plugins/Snippets/blob/master/Snippets.API.php#L232

**Comment by dregad** [comment]
Ah sorry, I guess you meant in the selection list
![snippet_list](https://user-images.githubusercontent.com/449891/37548985-56c8e764-297c-11e8-9c5f-6ba00700beab.png)

**Comment by dregad** [comment]
In fact I think this is a bug, caused by the fact that the PHP associative array generated by the route_data() method (and before conversion to REST API in v2.2.0, by the xmlhttprequest_plugin_snippets() function) is converted to a JSON _Object_ (i.e. an unordered collection) and not an _Array_.

Consequently, when the Snippets list is processed by the JavaScript to build the <select>, the entries are listed in ascending order of the snippet's ID instead of retaining the list's alphanumeric order.
