### ISSUE TITLE
After Upgrading to 2.3.1 the plugin's upgrade function crashes

### ISSUE THREAD

**Issue by FSD-Christian-ADM** [mantisbt-plugins/Snippets#55]
after upgrading the plugin, in the plugin overview it is said, that it needs to be upgraded. when clicking the upgrade button there is an Error in Block #1

when deactivating the line 174 in Snippets.php it doesn't need that upgrade and the plugin works back again. 

it seems that the plugin's init function is not executed to include the install_functions.php

using mantisbt 2.25.0 (upgraded from mantis 2.24.1)

**Comment by vboctor** [comment]
I have seen issues in MantisHub as part of upgrading to a release with to 2.3.1. This happens as part of the process to upgrade unattended which is run to upgrade core schema and plugin schemas. The snippet plugin upgrade fails. Downgrading back to 2.3.0 fixed the issue.

**Comment by FSD-Christian-ADM** [comment]
downgrading to 2.3.0 worked for me!

**Comment by dregad** [comment]
Confirmed - regression introduced by #54.

```
INTERNAL APPLICATION ERROR
call_user_func(): Argument `#1 ($function) must be a valid callback, function "install_delete_orphans" not found or invalid function name
```

Problem root cause is including the plugin's install functions in the _init()_ method, which is not called in upgrade context (plugin is only registered, not initialized).

The workaround to perform the upgrade with v2.3.0 as suggested by @vboctor is fine. Note that this upgrade step just performs some DB cleanup (removing orphan records, if there are any, see #52).
