### ISSUE TITLE
characters are problematic

### ISSUE THREAD

**Issue by imuratbayik** [mantisbt-plugins/Snippets#64]
Hello, thank you very much for this nice plugin.
Some of the Turkish characters are problematic. I mean,
The Turkish character is Ü Ç Ö I ç ö okey but, Ğ İ Ş ğ ı ş not okey.
These come out as question marks. ? in this way.
How can we/you fix this. Can you help me?

**Comment by dregad** [comment]
Not sure I understand the problem. Is it language strings (plugin UI), or snippet text (user data) ? On which page(s) ? Can you provide a better explanation (what you do, what you get, what you expect to get) and maybe provide screenshot(s) to illustrate ?

**Comment by dregad** [comment]
FYI This is what I get (copy/paste of your text above)... looks good to me

![image](https://user-images.githubusercontent.com/449891/208474917-2d40f45c-1be5-457a-978f-e41dbb7cfda3.png)

**Comment by imuratbayik** [comment]
plugin.php?page=Snippets/snippet_list
When I create a new snippet, it looks like the picture I added now.
Could it be something with the database structure? I am also attaching the database image.

![Ekran Resmi 2022-12-20 18 50 50](https://user-images.githubusercontent.com/26688308/208708764-c18f114f-9cb5-4d4d-97da-a9622977ddd9.jpg)
![Ekran Resmi 2022-12-20 18 48 00](https://user-images.githubusercontent.com/26688308/208708771-dc0ec06e-b894-4526-a067-93da7a5070ae.jpg)
![Ekran Resmi 2022-12-20 18 35 43](https://user-images.githubusercontent.com/26688308/208708774-64677efd-a9d4-41b0-b2bb-b35a803f2923.jpg)
![Ekran Resmi 2022-12-20 18 35 24](https://user-images.githubusercontent.com/26688308/208708776-4bc033b5-ee0c-4a83-94ea-c38b38957d39.jpg)
![Ekran Resmi 2022-12-20 18 35 59](https://user-images.githubusercontent.com/26688308/208708780-75eb44d8-fd74-49a9-a64f-3b9ee680771b.jpg)
![Ekran Resmi 2022-12-20 18 36 28](https://user-images.githubusercontent.com/26688308/208708781-24b0e3b6-c9e3-4937-bfca-9b3d65d6c383.jpg)

**Comment by dregad** [comment]
I see from your phpMyAdmin screenshot that you are using `utf8_general_ci` collation. In MySQL < 8.0, this actually defaults to the *utf8mb3* character set, which actually stores characters with 3 bytes instead of the 4 required to cover the full Unicode range, so it does not support all characters.

You most likely have the same problem throughout MantisBT, and not just Snippets, because the installer creates the tables like that. This is a [known issue](https://www.mantisbt.org/bugs/view.php?id=20431) with MantisBT.

You should convert your database (schema, tables and columns) to **utf8mb4**. There are plenty of resources explaining how to do that, e.g. https://dev.mysql.com/blog-archive/mysql-8-0-collations-migrating-from-older-collations/

I do not expect this migration to cause any issues, except a possible increase in size, but still you should make sure to have a backup at hand, just in case.

Since this is not an issue of the Snippets plugin, I'm going to close this.
